### ISSUE TITLE
[TW] Service-1.112.0 업데이트 항목

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#219]
@ysjo-wt Service-1.112.0 업데이트 항목 중 문서에 추가할 사항 정리합니다. 참고하시기 바랍니다.

---

### Preview 1.111.9

* [ ] ~~K8s - 노드 에이전트 1.3.7 버전부터 개편된 노드 목록 화면 제공~~
* [x] Browser - 분석 > AJAX 히트맵 메뉴 추가 -iM

### Preview 1.111.8

* [x] DB - 통계/보고서 > SQL 통계 메뉴의 사용자 편의성을 위한 UI 개선 -iM
* [x] DB - 대시보드 > 인스턴스 모니터링 메뉴에서 비실시간 모드 상태가 되면 해당 시간의 SQL 통계 메뉴로 이동할 수 있는 버튼 추가 -iM
* [x] DB - MS SQL Server 상품의 이름을 SQL Server로 변경 -iM
* [x] K8s - 트레이스 분석 기능 개선된 버전으로 교체

### Preview 1.111.6

* [x] 이용 내역 > 결제 정보 메뉴에서 통화 선택 기능 추가, 프로젝트 유료 전환, 청구서 미리보기, 청구 및 납부 내역에서 환율 토글 제거 -iM

### Preview 1.111.4

* [x] DB V2 - 로그 > 로그 설정 메뉴에서 설치형 DB, AWS RDS별 로그 설정 방법 설명 추가 -iM

### Preview 1.111.3

* [x] ~~Log - 로그 > 로그 설정 > 로그 1차 파서 설정 탭에서 파서를 추가할 경우, 로그 검출 조건의 검색 값 입력 시 예약어에 대한 유효성 검증 추가~~

**Comment by ysjo-wt** [comment]
@kijung-iM 네, 확인했습니다. 파싱 관련 로그 검출 조건 입력 안내 기술이 존재해 유효성 추가는 하지 않아도 될 것 같습니다.
