### ISSUE TITLE
[TW] 메트릭스 이벤트 추가 - 템플릿 관련 수정

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#244]
@ysjo-wt 

APM, Server, Kubernetes, Browser, NPM 상품을 제외하고는 경고 알림 > 이벤트 설정 메뉴에서 메트릭스 이벤트의 템플릿이 없는 경우가 있습니다.

- 템플릿이 없는 상품의 경우 관련 내용을 삭제 진행하고, 이후 추가되는 내용에 맞춰 문서 작업 진행하도록 합니다.
- Server, Kubernetes의 경우 공통 내용과 다른 별도의 템플릿이 있습니다. 기존대로 내용을 두되 빠른 시일내로 내용을 서비스에 맞게 업데이트하겠습니다.
- DB 상품의 경우 현재 템플릿이 존재하지 않습니다. DB 상품에 필요한 메트릭스 경고 알림 작성법을 학습하기 하위 문서로 추가할 예정입니다.

위 사항 참조하시기 바랍니다. 별도 의견이 있으시면 댓글 남겨 주세요.

**Comment by ysjo-wt** [comment]
네, 확인했습니다. 그럼 Server, K8s의 경우 템플릿 확인 후 추후 업데이트하겠습니다. 현재 Server는 Apdex 관련 알림 템플릿만 확인이 되네요.

**Comment by ysjo-wt** [comment]
docs bd596a9e

**Comment by ysjo-wt** [comment]
서브 복합 메트릭스 안내 작성 및 검수 후 메인에 병합 시켰습니다.
