### ISSUE TITLE
[TW] Service 1.114 업데이트 사항

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#297]
Service 1.114 업데이트 대비 문서 작성 및 수정 필요한 항목입니다.

@ysjo-wt 아래 추가할 항목이 있다면 자유롭게 작성 부탁드립니다.

- [ ] Kubernetes 
  - [x] ***POD** 초기화 성능* 메뉴명 변경 -> ***Pod** 초기화 성능* / 관련: https://whatap-labs.atlassian.net/browse/KUBER-277
  - [x] #307
  - [ ] (버그 수정 대기)#306
  - [x] #332
  - [x] #328
  - [x] #255
- [x] 참조 문서
  - [x] 정비 계획 V2
- [x] [Postgres V2 - 오브젝트 정보 메뉴추가](https://whatap-labs.atlassian.net/browse/SERVICE-378)
- [ ] ~~Preview 1.113.5: 이용내역 > 청구서 미리보기 > 사용량 가리기 옵션 추가 및 금액 표시 개선~~
    -> 해당 건은 https://billing.whatap.io/ 페이지에서 설정해야 가능한 기능이므로 docs에는 추가하지 않음
- [x] Preview 1.113.7: 경고 알림 > 이벤트 기록 메뉴에서 제목 외에도 메시지 필드에 대한 검색 기능 지원
- [x] Preview 1.113.8: DB - 통계/보고서 > SQL 통계 메뉴에서 막대 그래프를 클릭하면 5분 동안의 상세 통계 정보 창을 표시하는 기능 추가
- [x] Preview 1.113.8: DB - 경고 알림 > 이벤트 설정 메뉴에서 메트릭스 이벤트 추가 시 선택할 수 있는 이벤트 템플릿 추가
- [x] Preview 1.113.9: Log - 로그 1차 파서 설정, 로그 2차 파서 설정, 빠른 인덱스의 설정 내용을 JSON으로 내보내거나 가져오는 기능 추가
- Preview 1.113.10:
    - [x] K8s - 리소스 > 클러스터 요약 메뉴 추가
    - [ ] K8s - 대시보드 > 컨테이너 맵 메뉴에서 1분간 사라진 컨테이너/Pod의 블록을 표시하는 기능 추가
- Preview 1.113.11
    - [x] Browser - AJAX 히트맵 UI 변경 #329 
    - [ ] K8s - 네임스페이스 프로젝트의 Pod 초기화 성능 메뉴 제거
    - [x] DB 공통 - 인스턴스 모니터링, 멀티 인스턴스 모니터링 메뉴에서 액티브 세션 테이블 접는 기능 추가
    - [x] PostgreSQL - - Plan 조회를 json 형식으로 조회할 수 있는 기능 추가
    - [x] PostgreSQL/MySQL - UI 개선, 쿼리 및 Plang 조회 기능 위치 변경, Parameter 바인드 기본 수행
    - [x] Oracle - 테이블스페이스 사이즈 메뉴에서 정보를 접어서 보여주도록 폴딩 기능 추가

**Comment by ysjo-wt** [comment]
Pod 초기화 성능 메뉴명 변경, 노드 목록 문서, 정비 계획 V2 문서 건의 경우 모두 메인 외 브랜치에 작업 마쳤으며 배포 시점에 머지할 예정입니다.

**Comment by ysjo-wt** [comment]
노드 목록(#255) 추가적인 변경 사항이 있어 재대기 중인데, 수정 반영 시 다시 업데이트하겠습니다.

**Comment by ysjo-wt** [comment]
- 컨테이너 이벤트 탭의 경우 버그가 있어 해당 버그 픽스 시 이미지 업데이트 예정
- 그 외 모두 머지

**Comment by kijung-iM** [comment]
https://github.com/whatap/docs/commit/ef91393e48e15960426a879bd27645d98b4d4aef

@ysjo-wt 로그 설정에 내보내기/가져오기 기능 내용 추가했습니다. 검토해보시기 바랍니다.

**Comment by ysjo-wt** [comment]
> [ef91393](https://github.com/whatap/docs/commit/ef91393e48e15960426a879bd27645d98b4d4aef)
> 
> @ysjo-wt 로그 설정에 내보내기/가져오기 기능 내용 추가했습니다. 검토해보시기 바랍니다.

문서 내 기술 방식대로 JSON 표기 시 대문자로 수정하겠습니다.
