### ISSUE TITLE
[TW] Service 1.108.00 대비 문서 업데이트 항목

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#36]
@ysjo-wt Service 1.108.00 대비 문서 업데이트 항목입니다. 추가 필요한 사항이 있다면 기입해 주세요.

- [x] Preview 1.107.10 페이지 로드 히트맵 메뉴의 추가된 기능
- [x] Preview 1.107.09 컨테이너 맵 메뉴의 요약 보기의 태그 항목을 개요 탭으로 분리
- [x] 컨테이너 맵 필터 -> 이중 필터
- [x] preview 1.107.14 로그 설정 > 카테고리 및 로그 검출 조건 선택 UI 개선
- [x] Preview 1.107.14 DB V2
    - 프로젝트 멤버 중 수정 권한이 있는 멤버만 세션 킬 버튼이 노출되도록 변경
    - 테이블 컬럼 선택 모달 UI 변경
    - 위젯별 메트릭스 정보를 나타내는 인포 아이콘 추가
    - 제품 환경별(RDS, XOS) 탭 분리
    - 데이터베이스 사이즈 : CSV 다운로드 기능 추가
- [x] 로그 알림 설정 개편
    - 로그 이벤트 목록
    - 실시간 로그 이벤트
    - 복합 로그 이벤트

**Comment by kijung-iM** [comment]
@ysjo-wt 릴리스 노트 

https://www.notion.so/whatap/Service-1-108-00-41c7bfcc5dce43a79943cc03c3ea654e?pvs=4

**Comment by ysjo-wt** [comment]
#69 (머지 전)
