### ISSUE TITLE
[TW] Service-2.0.0 업데이트 사항

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#371]
@ysjo-wt 아래 사항 참조하시기 바랍니다. Service-2.0.0 업데이트 사항입니다.

참조: https://docs.whatap.io/release-notes/preview/preview-2_0_0x

프론트 배포 프로세스 변경: https://www.notion.so/whatap/8fcdaa1690c44a3c80915b0cc34929e9

예시, Preview-2.0.0.a0, Preview-2.0.0.a1, Preview-2.0.0.a2, ... Service-2.0.0 배포

---

## Preview-2.0.0.a7

- [ ] ~~K8s: 로그 > WhaTap 이벤트: #WhatapEvent 카테고리의 로그 데이터 조회 기능 추가~~

## Preview-2.0.0.a6

- [ ] ~~K8s: 리소스 > 클러스터 요약 메뉴에 Service, Ingress, Job, CronJob 오브젝트 목록 추가~~
- [ ] ~~K8s: 리소스 > 클러스터 요약 메뉴에 Total Capacity CPU(노드 총 CPU), Total Capacity Memory(노드 총 Memory) 위젯 추가~~
- [ ] ~~K8s: 리소스 > 퍼포먼스 요약 메뉴에 에이전트 설치 노드에서 실행 중인 컨테이너 수와 에이전트 설치 노드에서 실행 중인 Pod 수, 에이전트 설치 노드 수 위젯 추가~~
- [x] Log: 에이전트 옵션이 설정된 경우 로그 레벨을 표시하는 색상 표시 기능 추가

## Preview-2.0.0.a5

- [x] ~~K8s: 리소스 > 컨테이너 목록 메뉴에서 Node 컬럼 항목을 선택하면 해당 노드 목록이 필터링된 노드 목록 메뉴로 이동하는 기능 추가~~

## Preview-2.0.0.a4

* [x] Browser: 브라우저 모니터링 대시보드 메뉴에서 조회 시간 기준, 페이지 로드 수가 가장 많은 국가를 지도 위젯에 기본 표시하도록 수정

## Preview-2.0.0.a3

* [x] 경고 알림 > 이벤트 설정 메뉴에서 메트릭스 이벤트 추가 시 수신 테스트 기능 실행을 위한 필수 입력 조건 변경
* [x] DB: 에이전트 업데이트 메뉴 개편 https://github.com/whatap/docs/commit/defab022e8722c980e1f3a0954ff90b58087a5d5

## Preview-2.0.0.a2
* [x] NPM: 분석 > TCP 세션, UDP 세션 - 필터의 key 및 value에 대한 예시 값을 제공하는 방식 개선, 조건식을 수식으로 확인할 수 있도록 개선

## Preview-2.0.0.a1
* [x] APM: 대시보드 > 트랜잭션 맵 메뉴 개편 - 트레이스 분석 팝업 창 적용
* [x] 사이트 관리자: 접근 제어 메뉴 폐기 https://whatap-labs.atlassian.net/browse/SERVICE-350
* [x] DB-PostgreSQL: column, index 구성을 확인할 수 있는 기능 추가
* [x] NPM: 네트워크 토폴로지 UI 구성 요소 변경
* [x] Browser: 페이지 로드 히트맵, AJAX 히트맵 메뉴에서 사용자 ID 필터 항목 추가
* [ ] ~~K8s: 로그 > 쿠버네티스 이벤트 메뉴 추가~~
* [ ] ~~K8s: 멀티 서비스 히트맵, 커스텀 히트맵 메뉴의 일본어 메뉴 이름 수정~~

## Preview-2.0.0.a0
* [x] 청구서 미리보기 메뉴에서 사용량 수치를 클릭하면 사용량 상세 정보를 표시하는 기능 추가 https://github.com/whatap/docs/commit/5c191252dc1042b9a4939d737bacefc4d24a954e
* [x] 애플리케이션 대시보드 메뉴의 각 위젯에 툴팁 및 관련 정보, 다국어 지원 추가 https://github.com/whatap/docs/commit/d1f2b9dae36766d5d30379b510f6f7ba66e784dd
* [x] DB: 통계/보고서 > SQL 통계 메뉴에서 쿼리(query)에 마우스 오버 시 쿼리 미리보기 기능 추가 https://github.com/whatap/docs/commit/1f428fdc30bb1e75c0c5fbfed2d85a2ad9590f21
* [x] DB: 통계/보고서 > PG SQL 통계 메뉴에서 쿼리(query)에 마우스 오버 시 쿼리 미리보기 기능 추가 https://github.com/whatap/docs/commit/1f428fdc30bb1e75c0c5fbfed2d85a2ad9590f21
* [x] DB: 통계/보고서 > MYSQL SQL 통계 메뉴에서 쿼리(query)에 마우스 오버 시 쿼리 미리보기 기능 추가 https://github.com/whatap/docs/commit/1f428fdc30bb1e75c0c5fbfed2d85a2ad9590f21
* [x] K8s: 리소스 > Pod 목록, 애플리케이션 목록, 컨테이너 이미지 메뉴 추가
* [x] K8s: 관리 > 연계 프로젝트 관리 메뉴 추가
* [ ] ~~K8s: 연계 등록된 프로젝트가 있을 경우 트레이스 분석 > 테이블 뷰에서 SQL 대상 서버 정보 및 HTTPURLConnection 정보에 대해 연계 분석 뷰 제공~~
* [x] Log: 로그 검색, 라이브 테일 메뉴에서 로그 검색 필터 기능 개편

**Comment by ysjo-wt** [comment]
@kijung-iM 미체크로 남겨둔 건은 문서 기술이 불필요합니다.(e.g. 컬럼 추가건) 완료한 다른 작업도 금일 내 추가 기술하겠습니다.
