### ISSUE TITLE
[TW] 사이드 메뉴 개편에 따른 메뉴 경로 및 캡쳐 이미지 수정

### ISSUE THREAD

**Issue by kijung-iM** [whatap/docs#518]
@ysjo-wt 사이드 메뉴 개편에 따른 메뉴 경로 및 캡쳐 이미지 수정과 관련한 내용은 아래에 체크리스트로 관리하겠습니다.
작업할 내용에 본인의 이니셜을 남겨주세요.

- [x] whatap-overview 알림 발행 채널 지원(캡쳐)
- [x] quick-guide 빠른 시작하기 - iM
   - [x] 프로젝트 생성 공통 문서  - iM
- [x] mobile-app > OTP 인증하기  - iM
- [x] about-billing 와탭 결제 계정 안내  - iM
- [x] main-ui-intro 홈 화면 안내  - iM
- [x] openapi 오픈 API - ys
- [x] account/account-manage 계정 관리 - ys
- [x] account/mfa 멀티팩터 인증 - ys
- [x] project/project-manage 프로젝트 구조 및 멤버 권한 - ys
- [ ] project/group 그룹 관리 - ys
  - [ ] 영상 추가 작업 필요* 
  - [x] 그외
- [x] project/organization 조직 관리 - ys
- [x] project/integrated-manage 통합 관리 - ys
- [x] management/billing 결제 - iM

---

아래 문서 중 공통 문서가 있을 경우 댓글, 알림을 통해 관리하도록 하겠습니다.

- [x] APM (Java, PHP, Python, Node.js, .NET, Go)  - iM
    - [x] Flex 보드 화면 모드 (flexboard-mode) : 전체 공통 수정
    - [x] 토폴로지 - 유형별 토폴로지: 메뉴 경로 수정
    - [x] 메트릭스: APM 문서 수정
    - [x] 메트릭스 이상 탐지 전체 공통 수정
    - [x] 인스턴스 성능 관리
- [ ] #527
- [x] #541
- [x] DB (PostgreSQL, MySQL, Oracle, SQL Server, Tibero, CUBRID, Altibase, Redis, MongoDB)  - iM
- [x] Cloud (Amazon CloudWatch, Amazon ECS, AWS Log, Azure Monitor, Naver Cloud Monitoring, Oracle Cloud Monitor) -ys
- [x] NPM - iM
- [ ] Log, AWS Log - ys
- [x] URL - iM
- [x] Browser - iM
- [x] Extensions -ys

**Comment by ysjo-wt** [comment]
```[tasklist]
### 사이드 메뉴 개편 작업
-[ ] 테스트
```

**Comment by ysjo-wt** [comment]
공통, 경고 알림 수신 문서(set-receive-event)

**Comment by ysjo-wt** [comment]
메트릭스 이상 탐지, 메트릭스 조회, 메트릭스 차트 k8s 경로 안내 수정 필요*

**Comment by ysjo-wt** [comment]
[공통] 메트릭스 경고 알림 경로 안내 수정(k8s 특정 경로 안내 수정), 경고 알림 수신 설정 경로 안내 수정 예정*

**Comment by ysjo-wt** [comment]
[공통] 알림 메시지 사용자 정의 문서 수정
